name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - run: go mod download
      - name: test
        run: go test -v -race -coverprofile=cover.out ./...
      - uses: k1LoW/octocov-action@v1
      - uses: reviewdog/action-golangci-lint@v2
        with:
          fail_on_error: true
  determine_release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    outputs:
      will_release: ${{ steps.determine_release.outputs.new_release_published }}
    steps:
      - uses: actions/checkout@v4
      - id: determine_release
        uses: cycjimmy/semantic-release-action@v4
        with:
          dry_run: true
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ github.token }}
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - test
      - determine_release
    if: ${{ needs.determine_release.outputs.will_release }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: goreleaser/goreleaser-action@v5
        with:
          version: v1.26.2
          args: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
